// <auto-generated />
using System;
using Kdega.ScormEngine.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kdega.ScormEngine.Persistence.Migrations
{
    [DbContext(typeof(KseDbContext))]
    [Migration("20230920235326_InitScormEntities")]
    partial class InitScormEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.Base.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCommentFromLearner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CmiCoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("N")
                        .HasColumnType("int");

                    b.Property<string>("NComment")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NLocation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NTimestamp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CmiCoreId");

                    b.ToTable("CmiCommentFromLearners");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCommentFromLms", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CmiCoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("N")
                        .HasColumnType("int");

                    b.Property<string>("NComment")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NLocation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NTimestamp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScoIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CmiCoreId");

                    b.ToTable("CmiCommentFromLms");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("CompletionThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Credit")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Entry")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Exit")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LearnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LearnerScormPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LessonLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LessonMode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("LessonStatus")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ProgressMeasure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ScaledPassingScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScoreChildren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScoreMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ScoreMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ScoreRaw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ScoreScaled")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SessionTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SuccessStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TotalTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("CmiCores");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdlNavRequest")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdlNavRequestValidChoice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdlNavRequestValidContinue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdlNavRequestValidPrevious")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CmiComments")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CmiCommentsFromLms")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CmiCoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LaunchData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearnerName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("MasteryScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaxTimeAllowed")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScoIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ScormContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScormPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuspendData")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeLimitAction")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("TotalTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CmiCoreId");

                    b.HasIndex("ScormPackageId");

                    b.ToTable("CmiData");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CmiCoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InteractionTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Latency")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MsreplTranVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("N")
                        .HasColumnType("int");

                    b.Property<string>("NId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Result")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("StudentResponse")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timestamp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Weighting")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CmiCoreId");

                    b.ToTable("CmiInteractions");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteractionsCorrectResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("N")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId");

                    b.ToTable("CmiInteractionsCorrectResponses");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteractionsObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("InteractionN")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MsreplTranVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("N")
                        .HasColumnType("int");

                    b.Property<string>("ObjectiveId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId");

                    b.ToTable("CmiInteractionsObjectives");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiLearnerPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AudioCaptioning")
                        .HasColumnType("int");

                    b.Property<decimal?>("AudioLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CmiCoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DeliverySpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MsreplTranVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Text")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CmiCoreId");

                    b.ToTable("CmiLearnerPreferences");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CmiCoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MsreplTranVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("N")
                        .HasColumnType("int");

                    b.Property<string>("NCompletionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NProgressMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NScoreMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NScoreMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NScoreRaw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NScoreScaled")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NSuccessStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CmiCoreId");

                    b.ToTable("CmiObjectives");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.ScormSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CmiCoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LearnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScoIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CmiCoreId");

                    b.ToTable("ScormSessions");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.LearnerScormPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CmiCoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePassed")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastOpenedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LearnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ScormPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CmiCoreId")
                        .IsUnique();

                    b.HasIndex("ScormPackageId");

                    b.ToTable("LearnerScormPackages");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdlseqObjectivesGlobalToSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImsssSequencing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetadataLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScormPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Structure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScormPackageId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.OrganizationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdlcpCompletionThresholds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdlcpDataFromLms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdlcpTimeLimitAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdlnavPresentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifierRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImsssSequencing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParentItemId");

                    b.ToTable("OrganizationItems");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdlcpScormType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScormPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlBase")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScormPackageId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.ResourceDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentifierRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("ResourceDependencies");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.ResourceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("ResourceFiles");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.ScormPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultOrganizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManifestIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManifestMetadataLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManifestMetadataSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManifestMetadataSchemaVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManifestVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManifestXmlBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PackageFolderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceXmlBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScormVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFromManifest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFromUpload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ScormPackages");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCommentFromLearner", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", "CmiCore")
                        .WithMany("CommentFromLearners")
                        .HasForeignKey("CmiCoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiCore");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCommentFromLms", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", "CmiCore")
                        .WithMany("CommentFromLms")
                        .HasForeignKey("CmiCoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiCore");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiData", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", "CmiCore")
                        .WithMany("CmiData")
                        .HasForeignKey("CmiCoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kdega.ScormEngine.Domain.Entities.ScormPackages.ScormPackage", "ScormPackage")
                        .WithMany()
                        .HasForeignKey("ScormPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiCore");

                    b.Navigation("ScormPackage");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteraction", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", "CmiCore")
                        .WithMany("CmiInteractions")
                        .HasForeignKey("CmiCoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiCore");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteractionsCorrectResponse", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteraction", "CmiInteraction")
                        .WithMany("InteractionsCorrectResponses")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiInteraction");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteractionsObjective", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteraction", "CmiInteraction")
                        .WithMany("InteractionsObjectives")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiInteraction");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiLearnerPreference", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", "CmiCore")
                        .WithMany("CmiLearnerPreferences")
                        .HasForeignKey("CmiCoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiCore");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiObjective", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", "CmiCore")
                        .WithMany("CmiObjectives")
                        .HasForeignKey("CmiCoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiCore");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.ScormSession", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", "CmiCore")
                        .WithMany()
                        .HasForeignKey("CmiCoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiCore");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.LearnerScormPackage", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", "CmiCore")
                        .WithOne("LearnerScormPackage")
                        .HasForeignKey("Kdega.ScormEngine.Domain.Entities.ScormPackages.LearnerScormPackage", "CmiCoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kdega.ScormEngine.Domain.Entities.ScormPackages.ScormPackage", "ScormPackage")
                        .WithMany("LearnersScorms")
                        .HasForeignKey("ScormPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmiCore");

                    b.Navigation("ScormPackage");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.Organization", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.ScormPackages.ScormPackage", "ScormPackage")
                        .WithMany("Organizations")
                        .HasForeignKey("ScormPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScormPackage");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.OrganizationItem", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.ScormPackages.Organization", "Organization")
                        .WithMany("Items")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("Kdega.ScormEngine.Domain.Entities.ScormPackages.OrganizationItem", "ParentItem")
                        .WithMany("SubOrganizationItems")
                        .HasForeignKey("ParentItemId");

                    b.Navigation("Organization");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.Resource", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.ScormPackages.ScormPackage", "ScormPackage")
                        .WithMany("Resources")
                        .HasForeignKey("ScormPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScormPackage");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.ResourceDependency", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.ScormPackages.Resource", "Resource")
                        .WithMany("Dependencies")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.ResourceFile", b =>
                {
                    b.HasOne("Kdega.ScormEngine.Domain.Entities.ScormPackages.Resource", "Resource")
                        .WithMany("Files")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiCore", b =>
                {
                    b.Navigation("CmiData");

                    b.Navigation("CmiInteractions");

                    b.Navigation("CmiLearnerPreferences");

                    b.Navigation("CmiObjectives");

                    b.Navigation("CommentFromLearners");

                    b.Navigation("CommentFromLms");

                    b.Navigation("LearnerScormPackage")
                        .IsRequired();
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.LearnerScorms.CmiInteraction", b =>
                {
                    b.Navigation("InteractionsCorrectResponses");

                    b.Navigation("InteractionsObjectives");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.Organization", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.OrganizationItem", b =>
                {
                    b.Navigation("SubOrganizationItems");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.Resource", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Kdega.ScormEngine.Domain.Entities.ScormPackages.ScormPackage", b =>
                {
                    b.Navigation("LearnersScorms");

                    b.Navigation("Organizations");

                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
